"""Add call_tasks table

Revision ID: 003
Revises: 002
Create Date: 2026-04-30
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "call_tasks",
        sa.Column("task_id",            sa.String(36),  primary_key=True,
                  comment="UUID v4 pre-generated by main agent"),
        sa.Column("curator_id",         sa.String(64),  nullable=False,
                  comment="CRM user_id of the responsible executor"),
        sa.Column("call_id",            sa.String(64),  nullable=False,
                  comment="service_request_id from CRM"),
        sa.Column("transcript",         sa.Text(),      nullable=True,
                  comment="Full call transcript (decoding field)"),
        sa.Column("call_summary",       sa.Text(),      nullable=True,
                  comment="2-3 sentence summary of the call"),
        sa.Column("buyer_profile_json", sa.Text(),      nullable=True,
                  comment="JSON: extracted buyer profile"),
        sa.Column("quality_score_json", sa.Text(),      nullable=True,
                  comment="JSON: AI quality assessment"),
        sa.Column("proposed_actions",   sa.String(256), nullable=True,
                  comment="Comma-separated action keys"),
        sa.Column("status",             sa.String(16),  nullable=False,
                  server_default="pending_user",
                  comment="pending_user | completed | expired"),
        sa.Column("remind_count",       sa.Integer(),   nullable=False,
                  server_default="0"),
        sa.Column("last_reminded_at",   sa.DateTime(timezone=True), nullable=True,
                  comment="Timestamp of last reminder sent"),
        sa.Column("user_replied_at",    sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at",         sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at",         sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
    )

    op.create_index("ix_call_tasks_curator_id", "call_tasks", ["curator_id"])
    op.create_index("ix_call_tasks_call_id",    "call_tasks", ["call_id"])
    op.create_index("ix_call_tasks_status",     "call_tasks", ["status"])


def downgrade() -> None:
    op.drop_index("ix_call_tasks_status",     table_name="call_tasks")
    op.drop_index("ix_call_tasks_call_id",    table_name="call_tasks")
    op.drop_index("ix_call_tasks_curator_id", table_name="call_tasks")
    op.drop_table("call_tasks")
